[workspace]
resolver = "3"
members = ["ullam-cli", "ullam-common"]

[workspace.package]
license = "MIT"
edition = "2024"

[workspace.dependencies]
anyhow = "1.0"
clap = "4.6"
clap_derive = "4.6"

thiserror = "2.0"
tokio = { version = "1.52", features = [ "rt-multi-thread", "macros" ] }
futures-util = "0.3"
tracing = { version = "0.1", features = [] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# io
reqwest = { version = "0.13", features = ["json", "stream", "rustls"]}
hf-hub = { version = "1.0", features = [ "rustls-tls" ] }
async-openai = "0.41"

# utils
dirs = "6.0"

# types
url = { version = "2.5" }

# Llama unpack
tar = "0.4"
flate2 = "1.1"
zip = "8.6"

ullam-common = { path = "./ullam-common" }

[workspace.lints.rust]
rust_2018_idioms = "deny"
# missing_docs = "deny"
missing_debug_implementations = "allow"
future_incompatible = "deny"
unsafe-code = "deny"

[workspace.lints.clippy]
unused_async = "deny"
pedantic = "warn"
unwrap_used = "warn"
