[workspace]
resolver = "3"
members = ["ullam-cli", "ullam-common", "ullam-llm", "ullam-parser", "ullam-preprocessor"]

[workspace.package]
license = "MIT"
edition = "2024"

[workspace.dependencies]
# CLI
clap = "4.6"
clap_derive = "4.6"

# Async
tokio = { version = "1.52", features = ["rt-multi-thread", "macros"] }
futures-util = "0.3"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
schemars = "1.2"

# UAV
ardupilot-binlog = { version = "0.2", features = ["serde"] }
# binrw = { version = "0.15", features = ["verbose-backtrace"] }
# quick-xml = { version = "0.42", features = ["serialize"] }
# mavlink = { version = "0.18", default-features = false, features = [
#     "std",
#     "transport-tcp",
#     "transport-udp",
#     "transport-direct-serial",
#     "dialect-common",
#     "format-generated-code",
#     "tokio",
# ] }
# ardupilot-binlog = "0.2"

# io
reqwest = { version = "0.13", features = ["json", "stream", "rustls"] }
hf-hub = { version = "1.0", features = ["rustls-tls"] }
async-openai = "0.42"

# utils
dirs = "7.0"
anyhow = "1.0"
thiserror = "2.0"

# logging
tracing = { version = "0.1", features = [] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# types
url = { version = "2.5" }

# Llama unpack
tar = "0.4"
flate2 = "1.1"
zip = "8.6"

# local
ullam-common = { path = "./ullam-common" }
ullam-parser = { path = "./ullam-parser" }
ullam-preprocessor = { path = "./ullam-preprocessor" }
ullam-llm = { path = "./ullam-llm" }

[workspace.lints.rust]
rust_2018_idioms = "deny"
# missing_docs = "deny"
missing_debug_implementations = "allow"
future_incompatible = "deny"
unsafe-code = "deny"

[workspace.lints.clippy]
unused_async = "deny"
pedantic = "warn"
unwrap_used = "warn"
