[package]
name = "ullam-common"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
tracing.workspace = true
tokio = { workspace = true, features = ["process"]}
thiserror.workspace = true
anyhow.workspace = true

hf-hub.workspace = true
async-openai = { workspace = true, features = [ "full"]}
url = { workspace = true, features = [  "serde" ] }
dirs.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
futures-util.workspace = true

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
tar.workspace = true
flate2.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
zip.workspace = true