[package]
name = "ullam-ardupilot-log-types"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
binrw.workspace = true
serde.workspace = true
serde-big-array.workspace = true

[build-dependencies]
ullam-ardupilot-log-codegen = { path = "../ullam-ardupilot-log-codegen" }

[dev-dependencies]
serde_json.workspace = true