use std::fmt::Write;

use quick_xml::de::from_str;
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct LoggerMessageFile {
    #[serde(rename = "logformat", default)]
    formats: Vec<LogFormat>,
}

#[derive(Debug, Deserialize)]
struct LogFormat {
    #[serde(rename = "@name")]
    name: String,
    description: Option<String>,
    fields: Option<Fields>,
}

#[derive(Debug, Deserialize)]
struct Fields {
    #[serde(rename = "field", default)]
    fields: Vec<Field>,
}

#[derive(Debug, Deserialize)]
struct Field {
    #[serde(rename = "@name")]
    name: String,
    #[serde(rename = "@type")]
    ty: String,
}

/// Generate Rust source for the logger metadata XML document.
pub fn generate(xml: &str) -> Result<String, String> {
    let document: LoggerMessageFile = from_str(xml).map_err(|error| error.to_string())?;
    let mut output = String::from("// @generated by ardupilot-log-codegen; do not edit.\n\n");
    output.push_str("use binrw::{BinRead, BinWrite};\nuse serde::{Deserialize, Serialize};\n\n");

    for format in &document.formats {
        write_format(&mut output, format)?;
    }

    output.push_str("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n");
    output.push_str("#[serde(tag = \"message\", content = \"data\")]\n");
    output.push_str("pub enum Message {\n");
    for format in &document.formats {
        writeln!(&mut output, "    {}({}),", format.name, format.name)
            .expect("writing to a String cannot fail");
    }
    output.push_str("}\n");
    Ok(output)
}

fn write_format(output: &mut String, format: &LogFormat) -> Result<(), String> {
    let fields = format
        .fields
        .as_ref()
        .map_or(&[][..], |fields| fields.fields.as_slice());
    let description = format
        .description
        .as_deref()
        .unwrap_or_default()
        .replace('\n', " ");
    if !description.is_empty() {
        writeln!(output, "/// {description}").expect("writing to a String cannot fail");
    }
    output.push_str(
        "#[derive(Debug, Clone, PartialEq, BinRead, BinWrite, Serialize, Deserialize)]\n",
    );
    output.push_str("#[br(little)]\n#[bw(little)]\n");
    writeln!(output, "pub struct {} {{", format.name).expect("writing to a String cannot fail");
    for field in fields {
        let rust_name = identifier(&field.name);
        let rust_type = rust_type(&field.ty)?;
        if rust_name != field.name {
            writeln!(output, "    #[serde(rename = {:?})]", field.name)
                .expect("writing to a String cannot fail");
        }
        if matches!(rust_type, "[u8; 64]" | "[u8; 16]") {
            output.push_str("    #[serde(with = \"serde_big_array::BigArray\")]\n");
        }
        writeln!(output, "    pub {rust_name}: {rust_type},")
            .expect("writing to a String cannot fail");
    }
    output.push_str("}\n\n");
    Ok(())
}

fn identifier(name: &str) -> String {
    let mut result = String::new();
    for (index, character) in name.chars().enumerate() {
        if (index == 0 && character.is_ascii_digit())
            || (!character.is_ascii_alphanumeric() && character != '_')
        {
            result.push('_');
        } else {
            result.push(character);
        }
    }
    if result.is_empty() {
        "field".to_owned()
    } else if matches!(result.as_str(), "Err" | "Ok" | "Some" | "None") {
        format!("_{result}")
    } else if matches!(
        result.as_str(),
        "type"
            | "match"
            | "ref"
            | "self"
            | "Self"
            | "crate"
            | "super"
            | "move"
            | "async"
            | "await"
            | "loop"
            | "fn"
            | "struct"
            | "enum"
            | "use"
            | "mod"
            | "pub"
            | "const"
            | "static"
            | "where"
            | "impl"
            | "trait"
            | "for"
            | "in"
            | "let"
            | "return"
            | "if"
            | "else"
            | "while"
            | "break"
            | "continue"
            | "as"
            | "dyn"
            | "abstract"
            | "become"
            | "box"
            | "do"
            | "final"
            | "macro"
            | "override"
            | "priv"
            | "typeof"
            | "unsized"
            | "virtual"
            | "yield"
    ) {
        format!("r#{result}")
    } else {
        result
    }
}

fn rust_type(type_name: &str) -> Result<&'static str, String> {
    match type_name {
        "uint8_t" | "uint8_t flight mode" => Ok("u8"),
        "uint16_t" | "uint16_t * 100" => Ok("u16"),
        "uint32_t" => Ok("u32"),
        "uint64_t" => Ok("u64"),
        "int8_t" => Ok("i8"),
        "int16_t" | "int16_t * 100" => Ok("i16"),
        "int32_t" | "int32_t * 100" | "int32_t latitude/longitude" => Ok("i32"),
        "float" => Ok("f32"),
        "double" => Ok("f64"),
        "int16_t[32]" => Ok("[i16; 32]"),
        "char[4]" => Ok("[u8; 4]"),
        "char[16]" => Ok("[u8; 16]"),
        "char[64]" => Ok("[u8; 64]"),
        unsupported => Err(format!("unsupported ArduPilot logger type {unsupported:?}")),
    }
}

/// Generate Rust source from a logger metadata XML file.
pub fn generate_from_path(path: &std::path::Path) -> Result<String, String> {
    let xml = std::fs::read_to_string(path).map_err(|error| error.to_string())?;
    generate(&xml)
}
